force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>IF ( Annual_Revenue_Spent__c &gt;= 50000 , &quot;GOLD&quot;,
  IF ( Annual_Revenue_Spent__c &gt;= 25000 &amp;&amp; Annual_Revenue_Spent__c &lt; 50000 , &quot;SILVER&quot;,
  IF (Annual_Revenue_Spent__c &gt;= 10000 &amp;&amp; Annual_Revenue_Spent__c &lt; 25000 , &quot;BRONZE&quot;,&quot;&quot;
  ) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Logger__c/Exception_Logger__c.object-meta.xml
<CustomObject>
    <label>Exception Logger</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Exception Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Logger__c/fields/Class_Method__c.field-meta.xml
<CustomField>
    <fullName>Class_Method__c</fullName>
    <label>Class-Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendMessageToTwilioController.cls
/**
 * This is the controller call for the LWC component sendMessageToAccount
 **/
public class SendMessageToTwilioController {
    
    /**
     * This method is called to know the account type and get the phone number of an account.
     * */
    @AuraEnabled
    public static AccountDataWrapper getAccountData(String recId){
      Account acct = [Select Id,Name,Phone,Account_Type__c FROM Account where Id = :recId];
      AccountDataWrapper acctWrapper = new AccountDataWrapper();
      acctWrapper.acctName=acct.Name;
      acctWrapper.acctPhone=acct.Phone;
      acctWrapper.acctType=acct.Account_Type__c;
      return acctWrapper;
    }
    /**
     * This method is used to send an SMS to the respective account phone number.
     * */
    @AuraEnabled
    public static String sendSMSToAccount(String phoneNum){
        String msg;
        try{
        MessagingService.sendSMSUsingRestAPI(phoneNum,'You are a GOLD Customer');
        msg='Success';
        }catch(Exception e){
            msg='Excecption occurred'+e.getMessage();
            Exception_Logger__c eL = new Exception_Logger__c (Message__c=e.getMessage(),Line_Number__c=e.getLineNumber(),Class_Method__c	='SendMessageToTwilioController-sendSMSToAccount');
            insert eL;
        }
        return msg;
    }
    
  /*
   * Wrapper class used to store the Accoount required data. 
   * */
  public
  class AccountDataWrapper {
    @AuraEnabled public String acctName {
      get;
      set;
    }
    @AuraEnabled public String acctPhone {
      get;
      set;
    }
    @AuraEnabled public String acctType {
      get;
      set;
    }   
  }
   

}