force-app/main/default/objects/Account/fields/Annual_Revenue_Spent__c.field-meta.xml
<CustomField>
    <fullName>Annual_Revenue_Spent__c</fullName>
    <label>Annual Revenue Spent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/API_details__c/API_details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>API details</label>
</CustomObject>

force-app/main/default/objects/API_details__c/fields/accountSID__c.field-meta.xml
<CustomField>
    <fullName>accountSID__c</fullName>
    <label>accountSID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_details__c/fields/EndPointURL__c.field-meta.xml
<CustomField>
    <fullName>EndPointURL__c</fullName>
    <label>EndPointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_details__c/fields/FromPhone__c.field-meta.xml
<CustomField>
    <fullName>FromPhone__c</fullName>
    <label>FromPhone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MessagingServiceTest.cls
/**
 * Test class for the class MessagingService
 **/
@isTest
public class MessagingServiceTest {
    public static Account acct;
    @testSetup 
    public static void setup() {
        //Create custom setting
        API_details__c setting = new API_details__c();
        setting.Name = 'Twilio';
        setting.accountSID__c = 'ABC';
        setting.EndPointURL__c = 'https://api.twilio.com';
        setting.FromPhone__c = '+9188777656544';
        setting.Token__c = '12345';
        insert setting;
        
    }

    @isTest
    public static void sendSMSToCEOTest(){
       Test.setMock(HttpCalloutMock.class, new MessagingServiceMock());
       Set<Id> acctIds = new Set<Id>();
        acct  = new Account () ;
        acct.name ='Test Account';
        acct.phone = '+919886916030';
        acct.AnnualRevenue =3000000;
        acct.Annual_Revenue_Spent__c=400000;
        insert acct;
       acctIds.add(acct.Id);
       MessagingService.sendSMSToCEO(acctIds); 
    }
    
    @isTest
     public static void sendSMSToCEOAccountNegativeTest(){
         
         Test.setMock(HttpCalloutMock.class, new MessagingServiceMockNegative());
         Set<Id> acctIds = new Set<Id>();
        acct  = new Account () ;
        acct.name ='Test Account';
        acct.phone = '+919886916030000';
        acct.AnnualRevenue =3000000;
        acct.Annual_Revenue_Spent__c=400000;
        insert acct;
       acctIds.add(acct.Id);
         try{
              Test.startTest();
       MessagingService.sendSMSToCEO(acctIds);
             Test.stopTest();
         }catch(MessagingService.MyOtherException e){
             System.assert(true);
         }catch(Exception e){
             System.assert(true);
         }
    }
}